site_name: BraiNDy 2026
site_url: https://braindymeeting.github.io/v2026
copyright: Website maintained by BraiNDy Team.

theme:
  name: material
  logo: img/logo.ico
  favicon: img/logo.ico
  font:
    text: Varela
  palette:
    primary: black
    accent: blue

nav:
- About: index.md
- Schedule: schedule.md
- Invited Speakers: speakers.md 
- Team: team.md
- Previous Editions: previous.md
- Conference Material: slides_pics.md
